#!/usr/bin/env bash

# Copyright (C) 2014 Marc Blumenfrucht and Anne Jan Brouwer
# All Rights Reserved.
# This file is licensed under the GPLv2+. Please see COPYING for more information.

if [[ -z $1 ]]
then
	echo 'you need a password file'
	exit 1
fi

passresults=`pass $1`

passw=`echo "$passresults" | sed '1q;d'`
login=`echo "$passresults" | grep 'login:' | sed '1q;d'`
url=`echo "$passresults" | grep 'url:' | sed '1q;d'`

login=${login//login: /}
url=${url//url: /}

if [[ -z $login || -z $passw || -z $url ]]
then
	echo 'no complete credentials found'
	exit 1
fi

#sshline="ssh $login:$passw@$url"

sshline="sshpass -p$passw ssh -oStrictHostKeyChecking=no $login@$url"
$sshline
exitcode=$?
if [[ $exitcode -ne 0 ]]
then 
	echo 'could not log in'
	exit $exitcode
fi
